name: Build pull request
on: pull_request

permissions:
  contents: read

jobs:
  build:
    name: Build pull request
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Execute gradle test
      run: ./gradlew --info test

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit-files: "build/test-results/test/**/*.xml"
